name: py_test_api

services:
  tester:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile

    # set a volume to store the reports
    volumes:
        - reports:/py_test_api/reports

    # run pytest with allure package and keep the container running
    command: >
      sh -c "pytest -v --alluredir=py_test_api/reports
      && tail -F anything"

volumes:
  reports:

